blank_issues_enabled: true
contact_links:
  - name: Vortex Forums (Nexus Mods)
    url: https://forums.nexusmods.com/forum/4306-vortex-support/
    about: Please ask and answer questions here.
  - name: Discord (Nexus Mods)
    url: https://discord.gg/nexusmods
    about: Please ask and answer questions here.